### PR TITLE
First version

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/pytest-pymysql-autorecord/1)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
Are the tests supposed to be passing? They are failing from my side, it seems no data was stored to the files when applying `--mock-db-data` flag – files are created but they are empty and as such empty lists are returned when a flag `--mock-db-data`.

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-:-N5icyTq5TvtnwERg8ge:b-cbn4kj)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`docs/quickstart.md` line 9 at r1](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-N5iP9lS3UamZm_ZrdQq:-N5iP9lS3UamZm_ZrdQr:b-2wtvxc) ([raw file](https://github.com/saltastroops/pytest-pymysql-snapshot-mock/blob/e2d3568e5225e8d6e9d889e91a7e899734f482e5/docs/quickstart.md#L9)):*
> ```Markdown
> Hence, there may be a point in testing against "real" data. This works fine while testing on your own machine with access to the real database. But the moment you want to run tests on, say, GitHub, you run into a snag. From a security point of view, GitHub shouldn't have access to your database.
> 
> One way to solve the issue would be to use a local CI/CD pipeline, such as setting up a workflow o Jenkins. Another option would be to disable such tests when run on GitHub, which would fly against the idea of Continuous Integration.
> ```

... "such as setting up a workflow **on** Jenkins"
___
*[`docs/quickstart.md` line 43 at r1](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-N5iQ4eH5_lEM7X1dNKa:-N5iQ4eH5_lEM7X1dNKb:bhwh0w3) ([raw file](https://github.com/saltastroops/pytest-pymysql-snapshot-mock/blob/e2d3568e5225e8d6e9d889e91a7e899734f482e5/docs/quickstart.md#L43)):*
> ```Markdown
> ## Using the plugin
> 
> When you run pytest after installing pytest-pymysql-snapshot-mock, you will see no change; yiur real database connection is used and no data is stored.
> ```

yiur >>> your
___
*[`docs/quickstart.md` line 71 at r1](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-N5iQklwB0L2Qi-JVDRk:-N5iQklwB0L2Qi-JVDRl:bxquf3h) ([raw file](https://github.com/saltastroops/pytest-pymysql-snapshot-mock/blob/e2d3568e5225e8d6e9d889e91a7e899734f482e5/docs/quickstart.md#L71)):*
> ```Markdown
> But this poses a problem for mocking. Imagine that your test is checking that the created user has the correct username. When you run the test, a new username is generated, but the mocked database data contains the previously generated username. Clearly the two differ and the test fails.
> 
> To solve this issue, pytest-pymysql-snapshot-mock offers a fixture `database_mock` with a `user_value` method. If nbo mocking is used, this method returns the value passed to it, and if database data is being stored, it also saves this value. However, if the database is being mocked, `user_value` ignores its argument and instead returns the previously stored value.
> ```

nbo >>> no
___
*[`src/pytest_pymysql_snapshot_mock/plugin.py` line 12 at r1](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-N5idMMC0iQrqK051uSi:-N5idMMC0iQrqK051uSj:b-izg70l) ([raw file](https://github.com/saltastroops/pytest-pymysql-snapshot-mock/blob/e2d3568e5225e8d6e9d889e91a7e899734f482e5/src/pytest_pymysql_snapshot_mock/plugin.py#L12)):*
> ```Python
> 
> 
> def pytest_addoption(parser: pytest.Parser) -> None:
> ```

This line give's this error: `AttributeError: module 'pytest' has no attribute 'Parser'`

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1)* status: 15 of 17 files reviewed, 4 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`docs/quickstart.md` line 9 at r1](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-N5iP9lS3UamZm_ZrdQq:-N5p7ybA6vLHpv_uhbQB:b-d5q2i1) ([raw file](https://github.com/saltastroops/pytest-pymysql-snapshot-mock/blob/e2d3568e5225e8d6e9d889e91a7e899734f482e5/docs/quickstart.md#L9)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

... "such as setting up a workflow **on** Jenkins"
</blockquote></details>

Fixed. Thanks!
___
*[`docs/quickstart.md` line 43 at r1](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-N5iQ4eH5_lEM7X1dNKa:-N5p8-UU2vwBaXaL3X96:b-d5q2i1) ([raw file](https://github.com/saltastroops/pytest-pymysql-snapshot-mock/blob/e2d3568e5225e8d6e9d889e91a7e899734f482e5/docs/quickstart.md#L43)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

yiur >>> your
</blockquote></details>

Fixed. Thanks!
___
*[`src/pytest_pymysql_snapshot_mock/plugin.py` line 12 at r1](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-N5idMMC0iQrqK051uSi:-N5p9TWT3oulCbyneFAD:bax342m) ([raw file](https://github.com/saltastroops/pytest-pymysql-snapshot-mock/blob/e2d3568e5225e8d6e9d889e91a7e899734f482e5/src/pytest_pymysql_snapshot_mock/plugin.py#L12)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

This line give's this error: `AttributeError: module 'pytest' has no attribute 'Parser'`
</blockquote></details>

This indeed does not work for version 5, but should for version 7. Fixed in the setup file.

**Review by mofokeng-chaka — COMMENTED** [review]
The above comment is still relevant, majority of the tests are still failing when using `--mock-db-data` flag.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-:-N676kuy7MF41x8pXLAF:bw0klsr)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

**Review by hettlage — COMMENTED** [review]
This turned put to be a known issue, which can be fixed by moving the line

```engine = create_engine(sdb_dsn, echo=echo_sql, future=True)```

into the `db_connection` fixture function.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-:-N67dUM9-L4ENXefg7wO:bex9ar4)* status: 15 of 17 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`docs/quickstart.md` line 71 at r1](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-N5iQklwB0L2Qi-JVDRk:-N67uwfF7swGI6dSGRbq:b6h3ulr) ([raw file](https://github.com/saltastroops/pytest-pymysql-snapshot-mock/blob/e2d3568e5225e8d6e9d889e91a7e899734f482e5/docs/quickstart.md#L71)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

nbo >>> no
</blockquote></details>

Should be fixed.

**Review by mofokeng-chaka — APPROVED** [review]
I am still having the same issue, I tried moving the code but it didn't work.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/pytest-pymysql-snapshot-mock/1#-:-N68It4pACwcDXz_TIez:bwsq95v)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
